name: numcol
description: A new Flutter project.

version: 2.1.0+18102201

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: "0.4.3"
  audioplayers: ^0.7.8
  share: "0.5.3"
  firebase_analytics: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: "3.0.0"

flutter:
  uses-material-design: true

  fonts:
    - family: Poiretone
      fonts:
        - asset: assets/fonts/poiretone.ttf
    - family: LemonMilk
      fonts:
        - asset: assets/fonts/LemonMilk.otf
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf

  assets:
    - assets/locale/i18n_en.json
    - assets/locale/i18n_fr.json
    - assets/locale/i18n_ca.json
    - assets/locale/i18n_es.json
    - assets/locale/i18n_gl.json
    - assets/locale/i18n_eu.json
    - assets/audio/click.mp3
    - assets/audio/gameover.mp3
    - assets/audio/start.mp3
    - assets/audio/wrong.mp3
