name: numcol
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  numcolengine:
    path: ./engine/
  shared_preferences: "0.4.3"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Poiretone
      fonts:
        - asset: fonts/poiretone.ttf
    - family: LemonMilk
      fonts:
        - asset: fonts/LemonMilk.otf
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf

  assets:
    - locale/i18n_en.json
    - locale/i18n_fr.json
    - locale/i18n_ca.json
    - locale/i18n_es.json
    - locale/i18n_gl.json
    - locale/i18n_eu.json
